name: equatable_lint_example
description: Package with every examples for the equatable_lint package
version: 0.1.2

publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  analyzer: ^5.10.0
  equatable: ^2.0.5

dev_dependencies:
  custom_lint: ^0.3.4
  equatable_lint:
    path: ../
