name: equatable_lint_example
description: Package with every examples for the equatable_lint package
version: 0.1.3

publish_to: none

environment:
  sdk: ">=3.1.0 <3.2.0"

dependencies:
  analyzer: 6.2.0
  equatable: 2.0.5

dev_dependencies:
  custom_lint: 0.5.2
  equatable_lint:
    path: ../
