name: equatable_lint
version: 0.2.3
description: This is a set of rules to make classes using Equatable more maintainable. We make sure here that every fields in an Equatable class is linked to the Equatable props getter.
homepage: https://github.com/bamlab/equatable_lint
repository: https://github.com/bamlab/equatable_lint

environment:
  sdk: ">=3.1.0 <3.2.0"

dependencies:
  analyzer: 6.2.0
  analyzer_plugin: 0.11.3
  collection: 1.18.0
  custom_lint_builder: 0.5.2
  equatable: 2.0.5
  source_gen: 1.4.0
